name: Deploy to Vercel

on:
  push:
    tags:
      - "*"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Vercel CLI
        run: npm i --global vercel@latest

      - name: Vercel Pull (prod)
        run: vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}

      - name: Configure Gitea Access Token
        run: git config --global url."https://${{ secrets.GITEA_TOKEN }}@gitea.sev-2.com".insteadOf ssh://gitea.sev-2.com

      - name: Generate env file
        run: |
          cat <<EOF > .env
          NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          EOF

      - run: yarn install 

      - name: Vercel Build
        run: vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}

      - name: Vercel Deploy (prebuilt)
        run: vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}
